# Gamification API: Progression
# OpenAPI 3.0 Contract

openapi: 3.0.3
info:
  title: Gamification API - Progression
  version: 1.0.0
  description: XP, level, streak, and multiplier endpoints

servers:
  - url: /api/gamification
    description: Gamification API base path

paths:
  /progression:
    get:
      operationId: getProgression
      summary: Get user's progression state
      description: Returns XP, level, streak, multiplier, and basic mascot info
      tags:
        - Progression
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User progression data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProgressionResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '402':
          $ref: '#/components/responses/PaymentRequired'

  /progression/history:
    get:
      operationId: getXPHistory
      summary: Get XP transaction history
      description: Returns paginated list of XP transactions
      tags:
        - Progression
      security:
        - bearerAuth: []
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
            maximum: 100
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: XP transaction history
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/XPHistoryResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '402':
          $ref: '#/components/responses/PaymentRequired'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  responses:
    Unauthorized:
      description: Missing or invalid authentication
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Unauthorized"

    PaymentRequired:
      description: Active subscription required
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Subscription required"
              redirectToPaywall:
                type: boolean
                example: true

  schemas:
    ProgressionResponse:
      type: object
      required:
        - xp
        - streak
        - mascot
      properties:
        xp:
          type: object
          required:
            - total
            - current_level
            - xp_in_level
            - xp_to_next
            - progress_percent
          properties:
            total:
              type: integer
              example: 2450
              description: Lifetime XP earned
            current_level:
              type: integer
              example: 12
              minimum: 1
              maximum: 100
            xp_in_level:
              type: integer
              example: 150
              description: XP progress in current level
            xp_to_next:
              type: integer
              example: 405
              description: XP required for next level
            progress_percent:
              type: integer
              example: 37
              minimum: 0
              maximum: 100
        streak:
          type: object
          required:
            - current
            - longest
            - multiplier
            - shields_available
          properties:
            current:
              type: integer
              example: 14
            longest:
              type: integer
              example: 21
            multiplier:
              type: number
              format: float
              example: 1.5
              minimum: 1.0
              maximum: 2.0
            shields_available:
              type: integer
              example: 2
              minimum: 0
              maximum: 3
        mascot:
          type: object
          required:
            - stage
            - stage_name
            - mood
            - energy
          properties:
            stage:
              type: integer
              example: 2
              minimum: 1
              maximum: 5
            stage_name:
              type: string
              example: "Ember"
              enum: ["Spark", "Ember", "Flame", "Blaze", "Inferno"]
            mood:
              type: string
              example: "proud"
              enum: ["celebrating", "proud", "happy", "neutral", "concerned", "sad", "sleeping"]
            energy:
              type: integer
              example: 85
              minimum: 0
              maximum: 100

    XPHistoryResponse:
      type: object
      required:
        - transactions
        - pagination
      properties:
        transactions:
          type: array
          items:
            $ref: '#/components/schemas/XPTransaction'
        pagination:
          type: object
          properties:
            total:
              type: integer
            limit:
              type: integer
            offset:
              type: integer

    XPTransaction:
      type: object
      required:
        - id
        - amount
        - reason
        - multiplier
        - created_at
      properties:
        id:
          type: string
          format: uuid
        amount:
          type: integer
          example: 18
          description: Final XP (after multiplier)
        base_amount:
          type: integer
          example: 15
          description: XP before multiplier
        reason:
          type: string
          example: "pillar_checkin"
          enum:
            - call_answered
            - call_completed
            - pillar_checkin
            - all_pillars_complete
            - promise_kept
            - promise_broken
            - achievement_unlock
            - daily_challenge
            - streak_bonus
            - level_up_bonus
            - admin_adjustment
        multiplier:
          type: number
          format: float
          example: 1.25
        metadata:
          type: object
          description: Context like call_id, pillar, achievement_key
        created_at:
          type: string
          format: date-time
