openapi: 3.0.0
info:
  title: YOU+ Account API
  version: 1.0.0
  description: User account and settings management

servers:
  - url: https://api.youplus.app
    description: Production

paths:
  /account/profile:
    get:
      summary: Get user profile
      tags:
        - Account
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User profile
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'

    put:
      summary: Update user profile
      tags:
        - Account
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                timezone:
                  type: string
                  example: 'America/New_York'
                display_name:
                  type: string
      responses:
        '200':
          description: Profile updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'

  /account/settings:
    get:
      summary: Get account settings
      tags:
        - Account
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Account settings
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountSettings'

    put:
      summary: Update account settings
      tags:
        - Account
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email_notifications:
                  type: object
                  properties:
                    transactional:
                      type: boolean
                      description: Receipts, password reset, etc.
                    marketing:
                      type: boolean
                      description: New features, tips
                call_reminders:
                  type: boolean
      responses:
        '200':
          description: Settings updated

  /account/email:
    put:
      summary: Change email address
      tags:
        - Account
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - new_email
                - password
              properties:
                new_email:
                  type: string
                  format: email
                password:
                  type: string
                  description: Current password for verification
      responses:
        '200':
          description: Verification email sent to new address
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'Confirmation email sent. Click the link to verify.'

  /account/password:
    put:
      summary: Change password
      tags:
        - Account
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - current_password
                - new_password
              properties:
                current_password:
                  type: string
                new_password:
                  type: string
                  minLength: 8
      responses:
        '200':
          description: Password updated
        '401':
          description: Current password incorrect

  /account/delete:
    post:
      summary: Request account deletion
      tags:
        - Account
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - password
                - reason
              properties:
                password:
                  type: string
                reason:
                  type: string
                  enum: ['not_using', 'privacy_concern', 'switching_services', 'other']
      responses:
        '200':
          description: Account deletion initiated
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'Confirmation email sent. Your account will be deleted in 30 days unless you cancel.'
                  grace_period_days:
                    type: integer
                    example: 30

  /account/delete/cancel:
    post:
      summary: Cancel pending account deletion
      tags:
        - Account
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Account deletion cancelled

  /account/trial:
    get:
      summary: Get trial status
      tags:
        - Account
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Trial info
          content:
            application/json:
              schema:
                type: object
                properties:
                  in_trial:
                    type: boolean
                  trial_end_date:
                    type: string
                    format: date-time
                  days_remaining:
                    type: integer

  /account/email-logs:
    get:
      summary: View email audit trail
      tags:
        - Account
      security:
        - bearerAuth: []
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
        - name: email_type
          in: query
          schema:
            type: string
            enum: ['welcome', 'password_reset', 'payment_receipt', 'subscription_change']
      responses:
        '200':
          description: List of emails sent to user
          content:
            application/json:
              schema:
                type: object
                properties:
                  emails:
                    type: array
                    items:
                      $ref: '#/components/schemas/EmailLog'

components:
  schemas:
    UserProfile:
      type: object
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
          format: email
        email_verified:
          type: boolean
        timezone:
          type: string
        display_name:
          type: string
          nullable: true
        created_at:
          type: string
          format: date-time
        last_login_at:
          type: string
          format: date-time
          nullable: true

    AccountSettings:
      type: object
      properties:
        email_notifications:
          type: object
          properties:
            transactional:
              type: boolean
            marketing:
              type: boolean
        call_reminders:
          type: boolean
        timezone:
          type: string

    EmailLog:
      type: object
      properties:
        id:
          type: string
          format: uuid
        email_type:
          type: string
          enum: ['welcome', 'password_reset', 'payment_receipt', 'subscription_change', 'failed_payment', 'call_reminder']
        sent_at:
          type: string
          format: date-time
        delivered_at:
          type: string
          format: date-time
          nullable: true
        failed_at:
          type: string
          format: date-time
          nullable: true

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
