openapi: 3.0.0
info:
  title: YOU+ Billing API
  version: 1.0.0
  description: Subscription and payment management

servers:
  - url: https://api.youplus.app
    description: Production

paths:
  /billing/checkout-link:
    post:
      summary: Generate payment checkout link
      tags:
        - Billing
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                trial_days_remaining:
                  type: integer
                  description: Optional - pre-fill for trial users
      responses:
        '200':
          description: Checkout link generated
          content:
            application/json:
              schema:
                type: object
                properties:
                  checkout_url:
                    type: string
                    format: uri
                    description: Redirect user to this URL for payment
                  expires_at:
                    type: string
                    format: date-time

  /billing/subscription:
    get:
      summary: Get user subscription status
      tags:
        - Billing
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Current subscription info
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubscriptionStatus'
        '401':
          description: Unauthorized

  /billing/subscription/cancel:
    post:
      summary: Cancel subscription at period end
      tags:
        - Billing
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Subscription cancellation scheduled
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: ['cancelled']
                  current_period_end:
                    type: string
                    format: date-time
                    description: Service continues until this date
        '400':
          description: Already cancelled or other error

  /billing/subscription/reactivate:
    post:
      summary: Reactivate cancelled subscription
      tags:
        - Billing
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Subscription reactivated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubscriptionStatus'
        '400':
          description: No cancelled subscription to reactivate

  /billing/history:
    get:
      summary: Get billing history (invoices and charges)
      tags:
        - Billing
      security:
        - bearerAuth: []
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: List of transactions
          content:
            application/json:
              schema:
                type: object
                properties:
                  transactions:
                    type: array
                    items:
                      $ref: '#/components/schemas/Transaction'
                  total_count:
                    type: integer

  /billing/payment-method:
    get:
      summary: Get saved payment method
      tags:
        - Billing
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Payment method info
          content:
            application/json:
              schema:
                type: object
                properties:
                  last_four:
                    type: string
                    description: Last 4 digits of card
                  brand:
                    type: string
                    description: Visa, Mastercard, etc.
                  expiry_month:
                    type: integer
                  expiry_year:
                    type: integer

    put:
      summary: Update payment method
      tags:
        - Billing
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - token
              properties:
                token:
                  type: string
                  description: Tokenized payment info from payment processor
      responses:
        '200':
          description: Payment method updated

  /webhooks/revenuecat:
    post:
      summary: RevenueCat webhook for subscription events
      tags:
        - Webhooks
      x-internal: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                event:
                  type: object
                  description: RevenueCat event payload
      responses:
        '200':
          description: Webhook processed

components:
  schemas:
    SubscriptionStatus:
      type: object
      properties:
        status:
          type: string
          enum: ['active', 'trialing', 'cancelled', 'expired']
          description: Current subscription state
        product_id:
          type: string
          description: YOU+ Pro or similar
        auto_renew:
          type: boolean
        current_period_start:
          type: string
          format: date-time
        current_period_end:
          type: string
          format: date-time
        cancel_at_period_end:
          type: boolean
        cancellation_reason:
          type: string
          nullable: true
        next_billing_date:
          type: string
          format: date-time
          description: When next charge will occur (null if cancelled)

    Transaction:
      type: object
      properties:
        id:
          type: string
          format: uuid
        type:
          type: string
          enum: ['charge', 'refund', 'adjustment']
        amount:
          type: number
          description: Amount in cents
        currency:
          type: string
          enum: ['USD', 'EUR', 'GBP']
        status:
          type: string
          enum: ['success', 'pending', 'failed', 'refunded']
        created_at:
          type: string
          format: date-time
        description:
          type: string
          example: 'YOU+ Pro weekly subscription'

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
